name: Vehiculo Tests Workflow

on:
  push:
    branches:
      - main
      - feature
      - feature/Billy

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '23'

      - name: Verify Java version
        run: java -version

      - name: Run Maven tests
        run: mvn test
